id: P004496
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:27:02.284604
source_metadata:
  id: bdr:W22326
  title: ཚུལ་ཁྲིམས་རྣམ་དག་བསྲུང་བའི་སྨོན་ཚིག
  author: ''
  volumes:
    3681c38466a7447ab9788cec53d38961:
      image_group_id: I1PD36255
      title: ''
      volume_number: 1
      total_pages: 12
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
