id: P004496
initial_creation_type: ocr
source_metadata:
  id: bdr:W22326
  title: ཚུལ་ཁྲིམས་རྣམ་དག་བསྲུང་བའི་སྨོན་ཚིག
  author: ''
  volumes:
    3681c38466a7447ab9788cec53d38961:
      image_group_id: I1PD36255
      title: ''
      volume_number: 1
      total_pages: 12
